# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: azureapp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  azure-app-path: '.'
  azure-webappname: 'githubactionsdemo1'
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        run: dotnet publish -c Release -o '${{env.azure-app-path}}/myapp'
      - name: Deploy
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: ${{env.azure-webappname}}
          slot-name: 'development'
          publish-profile: '${{secrets.AZURE_APP_SECRET}}'
          package: '${{env.azure-app-path}}/myapp'
